stages:
  - install_dependencies
  - delivery


delivery:
  stage: delivery
  image: node:latest
  services:
    - docker:dind
  variables:
    DOCKER_DRIVER: "overlay"
  # cache: 
  #   key: $CI_COMMIT_REF_SLUG-$CI_PROJECT_DIR
  #   paths:
  #     - website/node_modules/
  #   policy: pull

  script:
    - npm install dws-cli
    - npm install
    - npm run build
    - echo ${CI_PROJECT_NAME} 

    - node_modules/.bin/dws login --token ${USER_TOKEN}
    - node_modules/.bin/dws whoami # verify login
    - node_modules/.bin/dws rm  --name ${CI_PROJECT_NAME} --path . -Y
    - node_modules/.bin/dws add --name ${CI_PROJECT_NAME} --wrap false --path ./public

  after_script:
    - echo "Done!"