backend:
  name: gitlab
  branch: master
  repo: {{ repo_path }}
  auth_type: implicit
  app_id: 967a7b98a744c5aec6ab007d15d16b8bc08a9597c87340a7e07fdb03c94d8b34

site_url: {{ site_url }}

publish_mode: editorial_workflow

media_folder: static/assets
public_folder: /assets
collections:
  - name: blog
    label: Blog
    folder: _data/blog
    slug: '{{year}}-{{month}}-{{day}}-{{slug}}'
    create: true
    fields:
      - {
          label: Template,
          name: template,
          widget: hidden,
          default: BlogPost,
        }
      - { name: path, label: Path }
      - { name: date, label: Date, widget: datetime }
      - { name: title, label: Title }
      - label: Featured Image
        name: thumbnail
        widget: image
        hint: "Image size 1280x800 works best :)"
        required: false
        media_library:
          config:
            multiple: false
      - { name: body, label: Body, widget: markdown }
      - label: Meta Description
        name: metaDescription
        widget: text
        required: false
